# Generated by Django 3.1.5 on 2021-01-29 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AcceptedLoan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('confirmed_at', models.DateField(auto_now_add=True)),
            ],
            options={
                'ordering': ['confirmed_at'],
            },
        ),
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('annual_interest_rate', models.FloatField()),
                ('created_at', models.DateField(auto_now_add=True)),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='RequestedLoan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loan_amount', models.FloatField()),
                ('loan_period', models.IntegerField()),
                ('lenme_fee', models.FloatField(default=3.0)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('status', models.CharField(choices=[('Requested', 'Requested'), ('Funded', 'Funded'), ('Completed', 'Completed')], default='Requested', max_length=9)),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
