# Generated by Django 3.1.5 on 2021-01-29 10:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('loans', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='requestedloan',
            name='borrower',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loans', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='offer',
            name='investor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='investments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='offer',
            name='loan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offers', to='loans.requestedloan'),
        ),
        migrations.AddField(
            model_name='acceptedloan',
            name='accepted_offer',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='accepted_loan', to='loans.offer'),
        ),
        migrations.AddField(
            model_name='acceptedloan',
            name='requested_loan',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='accepted_loan', to='loans.requestedloan'),
        ),
    ]
